apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "gluster-heketi"
provisioner: kubernetes.io/GlusterFS
parameters:
  resturl: "http://172.20.1.20:8080" # Heketi Server 주소
  restuser: "admin"
  restuserkey: "admin"
