# PV를 마운트하는 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client
spec:
  replicas: 3

  selector:
    matchLabels:
      app: ubuntu

  template:
    metadata:
      labels:
        app: ubuntu

    spec:
      containers:
        - name: ubuntu
          image: ubuntu:16.04
          volumeMounts:
            - name: nfs
              mountPath: /mnt

          # 컨테이너 종료 방지를 위한 명령어
          command: ["/usr/bin/tail", "-f", "/dev/null"]

      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs-1
