# 초기화 전용 컨테이너
apiVersion: v1
kind: Pod
metadata:
  name: init-sample
spec:
  # 메인 컨테이너
  containers:
    - name: main
      image: ubuntu
      command: ["/bin/sh"]
      args: ["-c", "tail -f /dev/null"]
      volumeMounts:
        - mountPath: /docs
          name: data-vol
          readOnly: false

  # 메인 컨테이너 실행 전 실행되는 초기화 전용 컨테이너 정의
  initContainers:
    - name: init
      image: alpine

      ## 공유 볼륨에 디렉터리 작성, 소유자 변경 작업 실행
      command: ["/bin/sh"]
      args: ["-c", "mkdir /mnt/html; chown 33:33 /mnt/html"]
      volumeMounts:
        - mountPath: /mnt
          name: data-vol
          readOnly: false

  volumes:
    - name: data-vol
      emptyDir: {}
